### PR TITLE
Add "My events" listing

### PR DESCRIPTION
**Pull request by richsage**
https://joindin.jira.com/browse/JOINDIN-336

This adds a My Events listing alongside the existing Hot/Upcoming/Past listings.

When adding this, it messed the tab layout up and felt a bit cramped - I switched it to a `ViewPager` with a title bar, which also allows swiping left-right between views, rather than needing to tap on the title (you can still do that).

Users who aren't signed in get prompted to on the My Events page - the existing dialog box (used in the app settings currently) is used if they choose to do so. Not sure on the wording - feels a bit dry!

Styling was based on the joind.in turquoise, and then I styled the `ActionBar` to match also.

Some screenshots:
my-events-not-signed-in
my-events-sign-in-dialog
my-events-signed-in
hot-events

### CODE REVIEW

**Comment by richsage** [comment]
Note that for current app builds, users will need to sign out and back in again - the current release doesn't store user URIs when a user signs in.

**Comment by lornajane** [comment]
I love the way this looks and feels (I actually can't click on the column headings but I didn't try until I actually read that I should be able to).  I have it compiled and running on my machine.

I can't log in though, I get the message "Some configuration is missing. Try reinstalling?".  I like that it prompted me to do so in order to show me my events, that is really helpful.

**Comment by richsage** [comment]
Ah it sounds like you don't have the OAuth config file in place - there's a link from the README that mentions how to configure. That's the "configuration" error you're seeing... (on the github phone app so can't link presently!)

**Comment by richsage** [comment]
The changes here now also detect if a user was signed in with a previous version of the app, and then grab the necessary user details in the background when required, so that My Events can be shown accordingly.

**Comment by lornajane** [comment]
Thanks for the advice and the rebase, I have it all set up now (connected to the test platform) and it looks good but I can crash it repeatedly, sorry.  Go to My Events and load the list, then go somewhere else and mark yourself attending another event, then go back to My Events ... it seems to get confused and I'm not sure how to debug.

**Comment by richsage** [comment]
Ah I've just experienced this first-hand at phpsc :) will investigate...

**Comment by richsage** [comment]
@lornajane this should now not crash when you move around between the various views :)

**Comment by lornajane** [comment]
This could easily be something I'm doing wrong but now I get an IO Stream Related Error when I try to mark myself as attending on any event

**Comment by richsage** [comment]
hmm, just checking: network connection valid? did you need/have charles running ok?

**Comment by lornajane** [comment]
I needed to sign out and in again, and it's now working very well and looking excellent.  I don't think you want me to actually merge it but it gets enthusiastic nodding from me

**Pull request merged**
